# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=300, null=True)),
                ('mobile', models.IntegerField(blank=True, max_length=300, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('nid', models.IntegerField(blank=True, max_length=17, null=True)),
                ('profile_picture', models.ImageField(blank=True, max_length=500, null=True, upload_to=b'')),
                ('nid_picture', models.ImageField(blank=True, max_length=500, null=True, upload_to=b'')),
                ('gcm_register', models.IntegerField(blank=True, max_length=500, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(choices=[('D', 'Driver'), ('P', 'passenger')], default='Driver', max_length=200)),
                ('connected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
