# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20160314_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gcm_register',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
